name = "Eirene"
uuid = "9c0f25c4-2ca1-5870-89f6-52640788da1d"
keywords = ["topological data analysis", "persistent homology"]
license = "GNU"
desc = "High-performance persistent homology calculation, with generators."
version = "1.3.5"
author = "Gregory Henselman-Petrusek <gh10@princeton.edu>"

[deps]
Blink = "ad839575-38b3-5650-b840-f874b8c74a25"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Hungarian = "e91730f6-4275-51fb-a7a0-7064cfbd3b39"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"


[compat]
julia             = ">=1"
Blink             = ">=0.12.0"
CSV               = ">=0.5.16"
Colors            = ">=0.9.6"
Distances         = ">=0.8.2"
Hungarian         = ">=0.4.0"
JLD               = ">=0.9.1"
MultivariateStats = ">=0.7.0"
PlotlyJS          = ">=0.13.0"
